apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-greet-app
  labels:
    app: greet
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
      - name: node-greet-app
        image: mareh786/test-app:v21
        ports:
        - containerPort: 3000

