apiVersion: v1
kind: Service
metadata:
  name: greet-service
  namespace: test-app
spec:
  selector:
    app: greet
  ports:
    - protocol: TCP
      port: 3000       # Service port (exposed externally)
      targetPort: 3000 # Container port
  type: LoadBalancer
