apiVersion: v1
kind: Service
metadata:
  name: node-greet-app-service
    labels:
      app: greet
spec:
  type: NodePort
  selector:
    app: greet
  ports:
    - port: 3000          
      targetPort: 3000    
      nodePort: 31000