name: CI pipeline for Nodejs App


on: workflow_dispatch


jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4
        -   name: Install Node.js
            uses: actions/setup-node@v4
            with: 
                node-version: '20.x'
        # -   name: Test
        #     run: |
        #             npm install --save-dev jest supertest
        #             npm test
        # -   name: Build
        #     run: npm install
        # -   name: Run the app, Check And kill
        #     run: |
        #             node app.js &
        #             APP_PID=$!
        #             sleep 10
        #             curl http://localhost:3000
        #             kill $APP_PID
        -    name: Login Docker-Hub
             uses: docker/login-action@v3
             with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -   name: Setting DOCKER
            uses: docker/setup-buildx-action@v3
        -   name: Build and push
            uses: docker/build-push-action@v6
            with: 
                    push: true
                    tags: mareh786/greet-app:v1