name: CI pipeline for Nodejs App
on: push
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4
        -   name: Install Node.js
            uses: actions/setup-node@v4
            with: 
                node-version: '20.x'
        -   name: Test
            run: |
                    npm install --save-dev jest supertest
                    npm test
